=== ilkkalilius/CICS-CTG/src/test/resources/interface/string-condition.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT dummyDataCondition (global?,entryDataSet)>


<!ATTLIST dummyDataCondition xmlns CDATA #FIXED "jp.co.ogis_ri.component.dummyString">

<!ATTLIST dummyDataCondition xmlns:xsi CDATA #FIXED "http://www.w3.org/2001/XMLSchema-instance">

<!ELEMENT global (namespaceDataSet?)>
<!ELEMENT namespaceDataSet (namespace*)>
<!ATTLIST namespace prefix CDATA #REQUIRED>
<!ATTLIST namespace namespaceURI CDATA #REQUIRED>

<!ELEMENT entryDataSet (entry+)>
<!ELEMENT entry (replyData+)>
<!ATTLIST entry name CDATA #REQUIRED>

<!ELEMENT replyData (conditionGroup)>
<!ATTLIST replyData file CDATA #REQUIRED>

<!ELEMENT conditionGroup (conditionGroup*,condition*,notOperator*)>
<!ATTLIST conditionGroup operator (and|or) "and" >
<!ELEMENT condition (offset,value)>
<!ELEMENT offset (start-offset,end-offset)>
<!ELEMENT value
(booleanValue|intValue|floatValue|longValue|stringValue|doubleValue|dateTimeValue)>
<!ELEMENT notOperator (conditionGroup,condition)>
<!ELEMENT start-offset (#PCDATA)>
<!ELEMENT end-offset (#PCDATA)>

<!ATTLIST booleanValue operator (equal|notEqual) "equal" >
<!ELEMENT booleanValue (#PCDATA)>


<!ATTLIST intValue operator (equal|notEqual|lessThan|greaterThan|lessThanOrEqual|greaterThanOrEqual) "equal" >
<!ELEMENT intValue (#PCDATA)>


<!ATTLIST floatValue operator (equal|notEqual|lessThan|greaterThan|lessThanOrEqual|greaterThanOrEqual) "equal" >
<!ELEMENT floatValue (#PCDATA)>


<!ATTLIST doubleValue operator (equal|notEqual|lessThan|greaterThan|lessThanOrEqual|greaterThanOrEqual) "equal" >
<!ELEMENT doubleValue (#PCDATA)>


<!ATTLIST longValue operator (equal|notEqual|lessThan|greaterThan|lessThanOrEqual|greaterThanOrEqual) "equal" >
<!ELEMENT longValue (#PCDATA)>


<!ATTLIST stringValue operator (equal|notEqual|lessThan|greaterThan|lessThanOrEqual|greaterThanOrEqual) "equal" >
<!ELEMENT stringValue (#PCDATA)>


<!ATTLIST dateTimeValue operator (equal|notEqual|lessThan|greaterThan|lessThanOrEqual|greaterThanOrEqual) "equal" >
<!ELEMENT dateTimeValue (#PCDATA)>

=== ilkkalilius/CICS-CTG/core/src/test/resources/interface/customer-string-test-condition.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE esb-interface SYSTEM "string-condition.dtd">
<dummyDataCondition xmlns="jp.co.ogis_ri.component.dummyString" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <entryDataSet>
    <entry name="sample-command">
      <replyData file="interface/bytes/sample_response_1.bytes">
        <conditionGroup operator="and">
          <condition>
            <offset>
              <start-offset>378</start-offset>
              <end-offset>386</end-offset>
            </offset>
            <value>
              <stringValue operator="equal">20060701</stringValue>
            </value>
          </condition>  
        </conditionGroup>
      </replyData>
      <replyData file="interface/bytes/sample_response_8.bytes">
        <conditionGroup operator="and">
        </conditionGroup>
      </replyData>
    </entry>

    <entry name="sample-null-command">
      <replyData file="interface/bytes/sample_response_1.bytes">
        <conditionGroup operator="and">
          <condition>
            <offset>
              <start-offset>378</start-offset>
              <end-offset>386</end-offset>
            </offset>
            <value>
              <stringValue operator="equal">20060701</stringValue>
            </value>
          </condition>  
        </conditionGroup>
      </replyData>
      <replyData file="interface/bytes/sample_response_10.bytes">
        <conditionGroup operator="and">
        </conditionGroup>
      </replyData>
    </entry>

    <entry name="sample-request-only-command">
      <replyData file="interface/bytes/sample_response_10.bytes">
        <conditionGroup operator="and">
          <condition>
            <offset>
              <start-offset>378</start-offset>
              <end-offset>386</end-offset>
            </offset>
            <value>
              <stringValue operator="equal">20060701</stringValue>
            </value>
          </condition>  
        </conditionGroup>
      </replyData>
      <replyData file="interface/bytes/sample_response_10.bytes">
        <conditionGroup operator="and">
        </conditionGroup>
      </replyData>
    </entry>

    <entry name="sample-reply-only-command">
      <replyData file="interface/bytes/sample_response_10.bytes">
        <conditionGroup operator="and">
          <condition>
            <offset>
              <start-offset>378</start-offset>
              <end-offset>386</end-offset>
            </offset>
            <value>
              <stringValue operator="equal">20060701</stringValue>
            </value>
          </condition>  
        </conditionGroup>
      </replyData>
      <replyData file="interface/bytes/sample_response_10.bytes">
        <conditionGroup operator="and">
        </conditionGroup>
      </replyData>
    </entry>
    <entry name="q2o0e">
      <replyData file="interface/bytes/sample_response_10.bytes">
        <conditionGroup operator="and">
          <condition>
            <offset>
              <start-offset>378</start-offset>
              <end-offset>386</end-offset>
            </offset>
            <value>
              <stringValue operator="equal">20060701</stringValue>
            </value>
          </condition>  
        </conditionGroup>
      </replyData>
      <replyData file="interface/bytes/sample_response_10.bytes">
        <conditionGroup operator="and">
        </conditionGroup>
      </replyData>
    </entry>
  </entryDataSet>
</dummyDataCondition>
